### ISSUE TITLE
[Bugfix] Pre-commit and checks not working properly

### ISSUE THREAD

**Issue by adiadd** [awslabs/Log-Analyzer-with-MCP#16]
The pre-commit hooks aren't working properly and it would be great to enhance PRs with CI commands. 

A solution would be to:
1. Implement pre-commit hooks for proper checks to run `pre-commit run --all-files`
2. Implement proper `.github/workflows` for easier PR reviews and CI actions

**Comment by rainfallseason** [comment]
Hello! I'm new to contributing to open source, but may I work on this issue?
Thank you in advance!

**Comment by rainfallseason** [comment]
@adiadd My guess is that the cause of the bug is the duplicate `id: ruff` entries in the pre-commit-config.yaml file. I think simply removing one of them should fix the issue.
Regarding the Actions, I believe it's fine to configure them to run `pre-commit run --all-files` on both push and pull request events.
Is my understanding correct?

**Comment by adiadd** [comment]
Yep, you're correct - so we the issue is two faced:
1. We'd need to add the proper [ruff-pre-commit](https://github.com/astral-sh/ruff-pre-commit), like so:

```
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.10
  hooks:
    # Run the linter
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter
    - id: ruff-format
```

and 

2. Yep! We'd just want to run that for now but we would want to set it up such that we can easily add future actions 😄 

Thank you so much!
